@startuml

skinparam linetype ortho

entity appointments {
    +id
    +tenant
    --
    appointment_type
    update_time
    tms_id
    tms_source
    site_id
    tractor_id
    gate_pass_number
    gp_open_time
    gp_close_time
    gp_close_type
    additional_attributes
    inbound_trailer_id
    outbound_trailer_id
}
entity assigned_rules {
    +tenant
    +id
    --
    update_time
    location_id
    rule_id
}
entity assignment_deliveries {
    +id
    +tenant
    --
    assignment_id
    delivery_id
    update_time
    site_id
}
entity assignments {
    +tenant
    +id
    --
    direction
    update_time
    appointment_id
    sequence_number
    trailer_id
    location_id
    site_id
}
entity buildings {
    +id
    +tenant
    --
    name
    archived
    site_id
    geofence_id
}
entity carrier_eligibility_rules {
    +id
    +tenant
    --
    tractor_owner
    trailer_owner
    load_status
}
entity carrier_rates {
    +tenant
    +id
    --
    carrier_id
    site_id
    trailer_type_id
    detention_rate_id
    archived
    update_time
    start_time
    type
    charge_interval
    charge_interval_units
    detention_rate
    disabled
    end_event
    free_time
    free_time_units
    intermodal
    max_fee
    ob_end_event
    ob_start_event
    origin_return_calc_method
    start_event
}
entity carrier_sites {
    +tenant
    +id
    --
    update_time
    carrier_id
    site_id
    active
}
entity carriers {
    +tenant
    +id
    --
    update_time
    carrier_code
    name
    owns_trailers
    owns_tractors
    archived
    fourkites_id
    auto_create_carrier_from_integration
    parent_carrier_id
}
entity ctpat_settings {
    +id
    +tenant
    --
    config
    enabled
    mandatory
    created_at
    updated_at
    created_by
    updated_by
}
entity custom_field_options {
    +tenant
    +id
    --
    custom_field_id
    name
    label
    value
}
entity custom_fields {
    +id
    +tenant
    --
    name
    label
    type
    additional_attributes
    description
}
entity customer_carriers {
    +tenant
    +id
    --
    customer_id
    carrier_id
    update_time
}
entity customers {
    +tenant
    +id
    --
    update_time
    name
    active
    customer_permalink
}
entity databasechangelog {
    --
    id
    author
    filename
    dateexecuted
    orderexecuted
    exectype
    md5sum
    description
    comments
    tag
    liquibase
    contexts
    labels
    deployment_id
}
entity databasechangeloglock {
    +id
    --
    locked
    lockgranted
    lockedby
}
entity deliveries {
    +id
    +tenant
    --
    name
    site_id
    update_time
    route_id
    bill_of_lading
    tms_id
    tms_source
    priority
    origin_id
    destination_id
    customer_id
    scheduled_arrival_start
    scheduled_arrival_end
    estimated_arrival_time
    actual_arrival_time
    scheduled_departure_start
    scheduled_departure_end
    actual_departure_time
    scheduled_load_id
    actual_load_id
    safety_check
    safety_check_time
    canceled
    external_url
    processed
    load_reference_numbers
    po_numbers
    reference_numbers
    expected_seal_number
    scheduled_carrier_id
    scheduled_trailer_name
    actual_load_mode
    tags
    want_time
    scheduled_trailer_type_id
    expected_seal_status
    expected_broker_id
    last_associated_trailer_id
    latest_appointment_id
}
entity delivery_groups {
    +id
    +tenant
    --
    group_id
    delivery_id
    update_time
    site_id
}
entity delivery_templates {
    +tenant
    +id
    --
    name
    template_type
    site_id
    load_status
    load_type
    process_status
    custom_fields
    update_time
    location_set_id
    deliveries
    archived
}
entity detention_rates {
    +tenant
    +id
    --
    detention_rate
    charge_interval
    charge_interval_units
    free_time
    free_time_units
    max_fee
    disabled
    archived
    intermodal
    start_event
    end_event
    ob_start_event
    ob_end_event
    origin_return_calc_method
}
entity docks {
    +tenant
    +id
    --
    update_time
    site_id
    name
    archived
    geofence_id
    zone_id
}
entity door_logs {
    +tenant
    +id
    --
    door_id
    name
    dock_id
    door_status
    archived
    building_code
    geofence_id
    zone_id
    updated_at
    deleted
    user_id
}
entity doors {
    +tenant
    +id
    --
    update_time
    name
    dock_id
    door_status
    door_x
    door_y
    door_width
    door_height
    door_rotation
    archived
    building_code
    geofence_id
    zone_id
}
entity driving_nodes {
    +id
    +tenant
    --
    location
    site_id
}
entity driving_paths {
    +tenant
    +id
    --
    parent_node_id
    child_node_id
    distance_in_meters
    site_id
}
entity erp_submissions {
    +tenant
    +id
    --
    erp_source
    erp_id
    submission_status
    event_payload
    submission_metadata
    update_time
    created_at
}
entity events {
    +tenant
    +id
    --
    update_time
    type
    start_time
    end_time
    data
    site_id
    level
    rule_id
    record_id
}
entity expected_load_history {
    +tenant
    +id
    --
    delivery_id
    creation_time
    load_id
    user_id
}
entity filter_values {
    --
    appointment_type
    conditon
    preferred_docks
    preferred_doors
    preferred_parking_lots
    preferred_parking_spots
    preferred_unassigned_locations
    site_owners
    destination
    trailer_type
    building_code
    detention_fee_status
    state
    usage
    broker_carrier
    status
    carrier
    current_docks
    current_doors
    current_parking_lots
    current_parking_spots
    current_unassigned_locations
    refrigeration_status
    pp_fuel_level
    load_status
    load_type
    process_status
}
entity fk_addresses {
    +tenant
    +id
    --
    site_id
    building_id
    update_time
}
entity fk_appointment_stops {
    +id
    +tenant
    --
    fourkites_id
    load_number
    stop_id
    status
    appointment_status
    update_time
}
entity fk_fk_addresses {
    +tenant
    +id
    --
    address_id
    fourkites_id
    update_time
}
entity fk_stops {
    +tenant
    +id
    --
    assignment_id
    address_id
    update_time
    checked
}
entity fk_tracking_loads {
    +tenant
    +id
    --
    fourkites_id
    load_number
    status
    update_time
}
entity fk_tracking_stops {
    +tenant
    +id
    --
    tracking_id
    stop_id
    fourkites_id
    update_time
}
entity form_layouts {
    +tenant
    +id
    --
    name
    site_id
    sections
}
entity freight {
    +tenant
    +id
    --
    update_time
    freight_code
    freight_type
    name
    description
    additional_attributes
    archived
}
entity freight_sites {
    +tenant
    +id
    --
    update_time
    freight_id
    site_id
}
entity gate_events {
    +id
    +tenant
    --
    site_id
    event_type
    event_data
    trailer_id
    created_at
    update_time
}
entity gates {
    +id
    +tenant
    --
    update_time
    name
    gate_code
    gate_function
    site_id
    archived
    geofence_id
}
entity geofence_site {
    +id
    +tenant
    --
    site_id
    geofence_id
}
entity geofences {
    +id
    +tenant
    --
    created_at
    update_time
    type
    location
    boundary
    archived
}
entity intermodal_origin_events {
    +id
    --
    created_time
    updated_time
    equipment_name
    event_time
    event_type
    source
    expired
}
entity item_bundles {
    +tenant
    +id
    --
    update_time
    quantity
    load_id
    freight_id
    audited
    supplier_site_id
}
entity load_types {
    +tenant
    +id
    --
    value
    additional_attributes
    archived
    update_time
}
entity loads {
    +id
    +tenant
    --
    update_time
}
entity location_move_times {
    +id
    +tenant
    --
    from_location_id
    to_location_id
    count
    average
    variance
    update_time
}
entity location_set_association {
    +id
    +tenant
    --
    location_id
    location_set_id
}
entity location_sets {
    +tenant
    +id
    --
}
entity locations {
    +id
    +tenant
    --
    type
    door_id
    dock_id
    parking_lot_id
    parking_spot_id
    geofence_id
}
entity move_request_events {
    +id
    +tenant
    --
    site_id
    event_type
    event_data
    trailer_id
    created_at
    update_time
}
entity move_request_queues {
    +tenant
    +id
    --
    user_id
    move_request_id
    priority
}
entity move_request_task_status {
    +id
    +tenant
    --
    task_id
    status_start_time
    status_end_time
    user_id
    trailer_id
    mover_type
    from_location_id
    to_location_id
    priority
    status
    rejected
    requestor_comments
    assignee_id
    assignee_comments
    assignment_reason
    temperature_display_unit
    temperature_set_point
    switcher_vehicle_id
    is_reopen
    assignment_logic
    trailer_status_id_at_task_creation
    planned_trailer_id
    planned_to_location_id
}
entity notifications {
    +id
    +tenant
    --
    subscription_id
    status
    history
    event_id
    created_at
    status_time
    archived
}
entity observed_load_history {
    +id
    +tenant
    --
    delivery_id
    creation_time
    load_id
    user_id
}
entity occupancy_sensor_events {
    +id
    +tenant
    --
    sensor_id
    enabled
    update_time
    event_start_time
    event_end_time
    occupancy_status
    tag_code
}
entity occupancy_sensors {
    +tenant
    +id
    --
    location_id
    code
    archived
    update_time
    site_id
}
entity page_events {
    +id
    +tenant
    --
    site_id
    user_id
    action
    event
    event_occurred_at
    event_recorded_at
}
entity parking_lots {
    +tenant
    +id
    --
    site_id
    name
    update_time
    defines_spots
    capacity
    deleted
    archived
    geofence_id
}
entity parking_spots {
    +id
    +tenant
    --
    parking_lot_id
    name
    spot_status
    update_time
    spot_x
    spot_y
    spot_width
    spot_height
    spot_rotation
    archived
    geofence_id
    zone_id
}
entity pg_stat_statements {
    --
    userid
    dbid
    toplevel
    queryid
    query
    plans
    total_plan_time
    min_plan_time
    max_plan_time
    mean_plan_time
    stddev_plan_time
    calls
    total_exec_time
    min_exec_time
    max_exec_time
    mean_exec_time
    stddev_exec_time
    rows
    shared_blks_hit
    shared_blks_read
    shared_blks_dirtied
    shared_blks_written
    local_blks_hit
    local_blks_read
    local_blks_dirtied
    local_blks_written
    temp_blks_read
    temp_blks_written
    blk_read_time
    blk_write_time
    temp_blk_read_time
    temp_blk_write_time
    wal_records
    wal_fpi
    wal_bytes
    jit_functions
    jit_generation_time
    jit_inlining_count
    jit_inlining_time
    jit_optimization_count
    jit_optimization_time
    jit_emission_count
    jit_emission_time
}
entity pg_stat_statements_info {
    --
    dealloc
    stats_reset
}
entity precool_task_status {
    +id
    +tenant
    --
    status_start_time
    status_end_time
    priority
    status
    rejected
    requestor_comments
    assignee_comments
    temperature_set_point
    task_id
    user_id
    trailer_id
    assignee_id
    assignment_reason
    temperature_display_unit
    switcher_vehicle_id
    is_reopen
    assignment_logic
    trailer_status_id_at_task_creation
    planned_trailer_id
    planned_to_location_id
}
entity preferred_trailer_locations {
    +id
    +tenant
    --
    update_time
    trailer_id
    location_id
}
entity product_protection_checks {
    +id
    +tenant
    --
    user_id
    trailer_id
    check_time
    temperature_checked
    fuel_level_checked
    refrigeration_status
    fuel_level
    temperature
    temperature_set_point
    temperature_range_min
    temperature_range_max
    temperature_display_unit
    source_type
    source_name
    mode_of_operation
    mode_of_operation_checked
}
entity product_protection_settings {
    +tenant
    +site_id
    --
    lot_enabled
    dock_enabled
    default_check_timeout
    default_warning_threshold
    default_alert_threshold
    defrost_check_timeout
    defrost_warning_threshold
    defrost_alert_threshold
    update_time
    auto_trigger
    auto_trigger_interval
    automated_refuel_task_enabled
    minimum_fuel_level
    refill_level
    both_varience_enabled
    mode_of_operation_enabled
    fuel_level_required
}
entity reason_codes {
    +id
    +tenant
    --
    site_id
    name
    description
    reason_code_type
    update_time
    archived
}
entity refuel_task_status {
    +tenant
    +id
    --
    status_start_time
    status_end_time
    priority
    status
    rejected
    requestor_comments
    assignee_comments
    assignment_reason
    task_id
    user_id
    trailer_id
    assignee_id
    fuel_level
    switcher_vehicle_id
    is_reopen
    assignment_logic
    trailer_status_id_at_task_creation
    planned_trailer_id
    planned_to_location_id
}
entity report_sites {
    +report_id
    +tenant
    +site_id
    --
    update_time
}
entity reports {
    +id
    +tenant
    --
    update_time
    created_at
    name
    template
    user_id
    columns
    filters
    shared_with
    is_shared_report
    last_modified_by
    filters_v2
}
entity rfid_tag_reads {
    +id
    +tenant
    --
    timestamp_of_read
    site_id
    signal_strength
    rfid
    tag_type_id
    tag_code
    switcher_vehicle_id
    switcher_driver
    latitude
    longitude
    heading
    speed
    distance_to_closest_location
    trailer_associated_with_rfid
    trailer_current_location_type
    trailer_current_location_id
    trailer_current_location_name
    status
    process_comments
    created_at
    invalid_payload
    post_process_required
    closest_parking_spot_id
    closest_parking_spot_name
    trailer_status_id
}
entity rules {
    +tenant
    +id
    --
    name
    description
    type
    conditions
    priority
    update_time
    site_id
    origin_locations
    condition_v2
    archived
    task_priority
}
entity saved_filters {
    +id
    +tenant
    --
    name
    filters
    archived
    shareable
    site_id
    user_id
    saved_filters_flow
    update_time
    is_favourite
    filters_v2
    filters_v3
}
entity scheduled_report_email_addresses {
    +id
    +tenant
    --
    scheduled_report_email_id
    email_address
}
entity scheduled_report_email_send_frequencies {
    +id
    +tenant
    --
    scheduled_report_email_id
    send_frequency
}
entity scheduled_report_emails {
    +tenant
    +id
    --
    name
    email_subject
    report_id
    created_at
    data_window_delta
    tz_name
    last_sent_at
    attachment_file_format
    site_ids
}
entity site_map_info {
    +site_id
    +tenant
    --
    update_time
    updated_by
    created_at
    created_by
    center_point
    default_zoom_level
}
entity site_settings {
    +tenant
    +site_id
    --
    loading_screens
    unloading_screens
    switcher_inactive_timeout
    update_time
    assign_move_requests
    product_protection
    use_proximity
    stale_threshold_minutes
    allow_OOS_move_requests
    emergency_message_duration_minutes
    switcher_app_config
    drive_by_config
    rfid_reader_config
    trailers_at_risk_time_interval
    table_properties
    trailer_name_max_length
}
entity site_settings_log {
    +tenant
    +id
    --
    site_id
    settings
    updated_at
    user_id
}
entity sites {
    +tenant
    +id
    --
    update_time
    name
    site_code
    site_type
    licensed
    archived
    additional_attributes
    geofence_id
    time_zone
    facility_master_id
}
entity subscribers {
    +tenant
    +id
    --
    user_id
    email
    additional_info
}
entity subscriptions {
    +tenant
    +id
    --
    event_type
    event_subtype
    notification_type
    subscriber_id
    archived
}
entity switcher_event_log {
    +id
    +tenant
    --
    event_data
    event_time
    created_at
}
entity switcher_status {
    +tenant
    +id
    --
    switcher_event_log_id
    switcher_id
    switcher_vehicle_id
    site_id
    status_start_time
    status_end_time
    logged_in
    screen
    event
    num_of_tasks_assigned
    task_id
    created_at
    next_switcher_status_id
}
entity switcher_status_summary {
    +id
    +tenant
    --
    interval_time
    switcher_id
    switcher_vehicle_id
    site_id
    logged_in_time
    task_screen_time
    home_screen_time
    inventory_screen_time
    product_protection_screen_time
    active_time_completed_tasks
    active_time_other_tasks
    inactive_time_with_tasks
    inactive_time_without_tasks
    total_move_tasks_completed
    total_move_tasks_rejected
    total_move_tasks_unassigned
    move_tasks_average_time_dispatched_to_unassigned
    move_tasks_average_time_dispatched_to_accepted
    move_tasks_average_time_accepted_to_rejected
    move_tasks_average_time_accepted_to_hooked
    move_tasks_average_time_hooked_to_completed
    move_tasks_average_time_dispatched_to_completed
    total_bump_tasks_completed
    total_bump_tasks_rejected
    total_bump_tasks_unassigned
    bump_tasks_average_time_dispatched_to_unassigned
    bump_tasks_average_time_dispatched_to_accepted
    bump_tasks_average_time_accepted_to_rejected
    bump_tasks_average_time_accepted_to_hooked
    bump_tasks_average_time_hooked_to_completed
    bump_tasks_average_time_dispatched_to_completed
    total_precool_tasks_completed
    total_precool_tasks_rejected
    total_precool_tasks_unassigned
    precool_tasks_average_time_dispatched_to_unassigned
    precool_tasks_average_time_dispatched_to_accepted
    precool_tasks_average_time_accepted_to_rejected
    precool_tasks_average_time_accepted_to_completed
    precool_tasks_average_time_dispatched_to_completed
    total_refuel_tasks_completed
    total_refuel_tasks_rejected
    total_refuel_tasks_unassigned
    refuel_tasks_average_time_dispatched_to_unassigned
    refuel_tasks_average_time_dispatched_to_accepted
    refuel_tasks_average_time_accepted_to_rejected
    refuel_tasks_average_time_accepted_to_completed
    refuel_tasks_average_time_dispatched_to_completed
    move_tasks_count_dispatched_to_unassigned
    move_tasks_count_dispatched_to_accepted
    move_tasks_count_accepted_to_rejected
    move_tasks_count_accepted_to_hooked
    move_tasks_count_hooked_to_completed
    move_tasks_count_dispatched_to_completed
    bump_tasks_count_dispatched_to_unassigned
    bump_tasks_count_dispatched_to_accepted
    bump_tasks_count_accepted_to_rejected
    bump_tasks_count_accepted_to_hooked
    bump_tasks_count_hooked_to_completed
    bump_tasks_count_dispatched_to_completed
    precool_tasks_count_dispatched_to_unassigned
    precool_tasks_count_dispatched_to_accepted
    precool_tasks_count_accepted_to_rejected
    precool_tasks_count_accepted_to_completed
    precool_tasks_count_dispatched_to_completed
    refuel_tasks_count_dispatched_to_unassigned
    refuel_tasks_count_dispatched_to_accepted
    refuel_tasks_count_accepted_to_rejected
    refuel_tasks_count_accepted_to_completed
    refuel_tasks_count_dispatched_to_completed
    manual_tasks_completed
    created_at
}
entity switcher_team_locations {
    +id
    +tenant
    --
    team_id
    location_id
    update_time
    preferred
}
entity switcher_team_memberships {
    +id
    +tenant
    --
    team_id
    user_id
    update_time
}
entity switcher_team_tasks {
    +id
    +tenant
    --
    team_id
    task_type
    update_time
}
entity switcher_team_unassigned_locations {
    +tenant
    +id
    --
    team_id
    eligible
    preferred
    update_time
}
entity switcher_team_vehicles {
    +tenant
    +id
    --
    team_id
    switcher_vehicle_id
    update_time
}
entity switcher_teams {
    +tenant
    +id
    --
    site_id
    name
    description
    update_time
    archived
}
entity switcher_vehicles {
    +tenant
    +id
    --
    site_id
    name
    description
    switcher_id
    archived
    location
    heading
    speed
}
entity tag_types {
    +tenant
    +id
    --
    name
    prefix
    default
    archived
    update_time
    created_at
    range_min
    range_max
}
entity tasks {
    +tenant
    +id
    --
    source_type
    source_name
    site_id
    requestor_id
    update_time
    created_time
    type
    notes
}
entity tasks_v2 {
    +tenant
    +id
    --
    site_id
    requestor_id
    source_type
    source_name
    created_time
    update_time
    type
    notes
    trailer_id
    mover_type
    from_location_id
    to_location_id
    temperature_set_point
    temperature_display_unit
    priority
    status
    rejected
    is_reopen
    requestor_comments
    assignee_comments
    assignee_id
    switcher_vehicle_id
    fuel_level
    trailer_status_id_at_task_creation
    planned_trailer_id
    planned_to_location_id
}
entity temperature_ranges {
    +tenant
    +id
    --
    site_id
    load_type
    minimum_temperature
    maximum_temperature
    update_time
    temperature_set_point
    temperature_display_unit
    disabled
    lower_variance
    upper_variance
}
entity tractors {
    +tenant
    +id
    --
    name
    carrier_id
    license_plate
    tractor_state
    tractor_country
    created_at
    update_time
    driver
}
entity trailer_checks {
    +id
    +tenant
    --
    trailer_id
    site_id
    update_time
    check_time
    check_direction
    tractor_id
    appointment_id
    guard_id
    comments
    gate_id
    turnaway_reason_code
    check_in_source
    check_out_source
    time_taken_checkin
    time_taken_checkout
    trailer_status_id
}
entity trailer_conditions {
    +tenant
    +id
    --
    value
    archived
    update_time
}
entity trailer_events {
    +tenant
    +id
    --
    site_id
    event_type
    event_data
    trailer_id
    created_at
    update_time
}
entity trailer_fees {
    +tenant
    +id
    --
    trailer_id
    update_time
    fee
    carrier_rate_id
    end_time
    start_time
}
entity trailer_history {
    +id
    +tenant
    --
    trailer_id
    name
    created_at
    device_number
    update_time
    carrier_id
    broker_id
    site_owner_id
    site_id
    process_status
    yusen_tag_id
    load_status_empty_timestamp
    load_status_full_timestamp
    process_status_unloaded_timestamp
    process_status_loaded_timestamp
    delivery_group
    seal
    seal_status
    location_id
    load_status
    load_type
    user_id
    ready
    damage
    damage_note
    audit
    audit_note
    out_of_service
    out_of_service_note
    usage
    old_tag_code
    condition
    comments
    switcher_vehicle_id
    tag_type_id
    tag_code
    latest_pp_check_id
    last_pp_temp_check_id
    last_pp_fuel_check_id
    last_tag_read_time
    building_code
    additional_attributes
    intermodal_origin_time
    status_start_time
    carrier_rates_id
    detention_start_timestamp
    risk_start_time
    check_in_time
    check_out_time
    detention_fees
    turnaway_reason_code
    expected_outbound_delivery
    location_source
    detention_rule
    detention_end_timestamp
    type_id
    ctpat_info
    last_driveby_validation_time
    expected_outbound_shipment_group_id
}
entity trailer_history_copy_failure {
    +tenant
    +id
    --
    query_string
    processed
}
entity trailer_history_tmp {
    +tenant
    +id
    --
    trailer_id
    name
    created_at
    device_number
    update_time
    carrier_id
    broker_id
    site_owner_id
    trailer_type_id
    site_id
    process_status
    yusen_tag_id
    load_status_empty_timestamp
    load_status_full_timestamp
    process_status_unloaded_timestamp
    process_status_loaded_timestamp
    delivery_group
    seal
    seal_status
    location_id
    load_status
    load_type
    user_id
    ready
    damage
    damage_note
    audit
    audit_note
    out_of_service
    out_of_service_note
    usage
    old_tag_code
    condition
    comments
    switcher_vehicle_id
    tag_type_id
    tag_code
    latest_pp_check_id
    last_pp_temp_check_id
    last_pp_fuel_check_id
    last_tag_read_time
    building_code
    load_status_time
    trailer_fees
    additional_attributes
    intermodal_origin_time
    status_start_time
    carrier_rates_id
    detention_start_timestamp
    risk_start_time
    check_in_time
    check_out_time
    detention_fees
    turnaway_reason_code
    expected_outbound_delivery
    location_source
    detention_rule
    detention_end_timestamp
}
entity trailer_live_replication_failure {
    +id
    +tenant
    --
    query_string
    processed
}
entity trailer_master {
    +id
    +tenant
    --
    name
    asset_id
    created_at
    update_time
    carrier_id
    device_number
}
entity trailer_pool_settings {
    +tenant
    +id
    --
    site_id
    carrier_id
    min_pool
    max_pool
    additional_attributes
    updated_at
    updated_by
}
entity trailer_queues {
    +id
    +tenant
    --
    location_id
    trailer_id
    position
    requestor_id
    additional_attributes
    task_priority
    requestor_comments
}
entity trailer_status {
    +id
    +tenant
    --
    update_time
    status_start_time
    status_end_time
    trailer_id
    delivery_group
    seal
    seal_status
    site_id
    location_id
    load_status
    load_type
    process_status
    user_id
    ready
    damage
    damage_note
    audit
    audit_note
    out_of_service
    out_of_service_note
    usage
    additional_attributes
    old_tag_code
    condition
    comments
    switcher_vehicle_id
    tag_type_id
    tag_code
    last_pp_fuel_check_id
    last_pp_temp_check_id
    latest_pp_check_id
    last_tag_read_time
    building_code
    carrier_id
    trailer_name
    trailer_type_id
    intermodal_origin_time
    broker_id
    site_owner_id
    expected_outbound_delivery
    location_source
    carrier_rates_id
    detention_start_timestamp
    risk_start_time
    ctpat_info
    last_driveby_validation_time
    additional_attributes_v2
    trailer_usage_id
    trailer_condition_id
    load_type_id
    expected_outbound_shipment_group_id
}
entity trailer_status_intermediate_log {
    +id
    +tenant
    --
    record
    processed
}
entity trailer_status_intermediate_logs_failure {
    +id
    +tenant
    --
    query_string
    processed
}
entity trailer_status_live_replication_failure {
    +tenant
    +id
    --
    query_string
    processed
}
entity trailer_tag_sites {
    +id
    +tenant
    --
    update_time
    trailer_tag_id
    eligible_site_id
}
entity trailer_tags {
    +tenant
    +id
    --
    update_time
    tag_code
    trailer_name
    carrier_id
    archived
    additional_attributes
    check_in_eligible
    check_out_eligible
    trailer_usage
    trailer_type_id
    tag_type_id
    trailer_usage_id
}
entity trailer_type_sites {
    +tenant
    +id
    --
    update_time
    trailer_type_id
    eligible_site_id
}
entity trailer_types {
    +id
    +tenant
    --
    name
    refrigerated
    is_swing_door
    archived
}
entity trailer_usage {
    +id
    +tenant
    --
    value
    archived
    update_time
}
entity trailers {
    +id
    +tenant
    --
    name
    created_at
    update_time
    carrier_id
    broker_id
    site_owner_id
    type_id
    process_status
    site_id
    device_number
    yusen_tag_id
    load_status_empty_timestamp
    load_status_full_timestamp
    process_status_loaded_timestamp
    process_status_unloaded_timestamp
    carrier_rates_id
    check_in_time
    check_out_time
    detention_start_timestamp
    detention_end_timestamp
    detention_fees
    detention_rule
    risk_start_time
    turnaway_reason_code
    additional_attributes_v2
}
entity trailers_copy_failure {
    +id
    +tenant
    --
    trailer_id
    processed
}
entity trailers_intermediate_logs {
    +tenant
    +id
    --
    record
    processed
}
entity trailers_intermediate_logs_failure {
    +id
    +tenant
    --
    query_string
    processed
}
entity trailers_v2 {
    +id
    +tenant
    --
    name
    created_at
    update_time
    device_number
    carrier_id
    broker_id
    site_owner_id
    site_id
    process_status
    yusen_tag_id
    load_status_empty_timestamp
    load_status_full_timestamp
    process_status_unloaded_timestamp
    process_status_loaded_timestamp
    delivery_group
    seal
    seal_status
    location_id
    load_status
    load_type
    user_id
    ready
    damage
    damage_note
    audit
    audit_note
    out_of_service
    out_of_service_note
    usage
    old_tag_code
    condition
    comments
    switcher_vehicle_id
    tag_type_id
    tag_code
    latest_pp_check_id
    last_pp_temp_check_id
    last_pp_fuel_check_id
    last_tag_read_time
    building_code
    additional_attributes
    intermodal_origin_time
    status_start_time
    carrier_rates_id
    check_in_time
    check_out_time
    detention_fees
    detention_start_timestamp
    risk_start_time
    turnaway_reason_code
    expected_outbound_delivery
    location_source
    detention_rule
    detention_end_timestamp
    type_id
    ctpat_info
    last_driveby_validation_time
    last_known_audit
    last_known_audit_note
    last_known_damage
    last_known_damage_note
    last_known_out_of_service
    last_known_out_of_service_note
    ever_damage
    ever_out_of_service
    last_location_update_time
    last_process_status_update_time
    last_load_status_update_time
    last_condition_update_time
    last_known_tag_code
    last_known_inside_process_status
    last_known_inbound_delivery_group
    last_known_outbound_delivery_group
    last_known_location_id
    first_assigned_processing_location_id
    last_comment_update_time
    last_audit_note_update_time
    last_damage_note_update_time
    last_out_of_service_note_update_time
    last_known_comment
    additional_attributes_v2
    trailer_usage_id
    trailer_condition_id
    load_type_id
    expected_outbound_shipment_group_id
    detention_configuration_at_checkin
    load_status_at_checkin
    detention_start_event
    detention_end_event
    time_on_site
}
entity trailers_v2_tmp {
    +tenant
    +id
    --
    name
    created_at
    update_time
    device_number
    carrier_id
    broker_id
    site_owner_id
    trailer_type_id
    site_id
    process_status
    yusen_tag_id
    load_status_empty_timestamp
    load_status_full_timestamp
    process_status_unloaded_timestamp
    process_status_loaded_timestamp
    delivery_group
    seal
    seal_status
    location_id
    load_status
    load_type
    user_id
    ready
    damage
    damage_note
    audit
    audit_note
    out_of_service
    out_of_service_note
    usage
    old_tag_code
    condition
    comments
    switcher_vehicle_id
    tag_type_id
    tag_code
    latest_pp_check_id
    last_pp_temp_check_id
    last_pp_fuel_check_id
    last_tag_read_time
    building_code
    load_status_time
    trailer_fees
    additional_attributes
    intermodal_origin_time
    status_start_time
    carrier_rates_id
    check_in_time
    check_out_time
    detention_fees
    detention_start_timestamp
    risk_start_time
    turnaway_reason_code
    expected_outbound_delivery
    location_source
    detention_rule
    detention_end_timestamp
}
entity translation_overrides {
    +id
    +tenant
    --
    locale
    translation_key
    translation_value
}
entity user_carriers {
    +tenant
    +id
    --
    user_id
    carrier_id
    update_time
}
entity user_history {
    +id
    +tenant
    --
    user_id
    event_time
    active
    logged_in
    user_initiated
    generated_by
}
entity user_site_preferences {
    +tenant
    +id
    --
    site_id
    user_id
    docks
    tasks
    created_at
    updated_at
}
entity user_sites {
    +tenant
    +id
    --
    user_id
    site_id
    update_time
}
entity users {
    +id
    +tenant
    --
    first_name
    last_name
    email_address
    expires_in
    create_time
    update_time
    archived
    keycloak_id
    heartbeat
    type
    language
    language_code
    created_by
    updated_by
    updated_at
}
entity webhooks {
    +id
    +tenant
    --
    trigger_event
    url
    name
    description
    authentication_method
    headers
}
entity yard_properties {
    +tenant
    +id
    --
    property
    option_name
    additional_attributes
    zone_id
}
entity zones {
    +id
    +tenant
    --
    name
    description
    site_id
    geofence_id
    archived
    clean_up
    update_time
}

appointments --{ assignments :assignments_appointment_id_fkey
appointments --{ deliveries :deliveries_latest_appointment_id_fkey
appointments --{ trailer_checks :trailer_checks_appointment_id_fkey
assignments --{ assignment_deliveries :assignment_deliveries_assignment_id_fkey
assignments --{ fk_stops :fk_stops_assignment_id_fkey
buildings --{ fk_addresses :fk_addresses_building_id_fkey
carrier_rates --{ trailer_fees :trailer_fees_carrier_rate_id_fkey
carrier_rates --{ trailer_status :trailer_status_carrier_rates_id
carrier_rates --{ trailers :trailers_carrier_rates_id
carrier_rates --{ trailer_history :trailers_history_carrier_rates_id
carrier_rates --{ trailer_history_tmp :trailers_history_carrier_rates_id
carrier_rates --{ trailers_v2 :trailers_v2_carrier_rates_id
carrier_rates --{ trailers_v2_tmp :trailers_v2_carrier_rates_id
carrier_rates --{ trailers_v2 :trailers_v2_detention_configuration_at_checkin
carriers --{ carrier_eligibility_rules :carrier_eligibility_rules_tractor_owner_fkey
carriers --{ carrier_eligibility_rules :carrier_eligibility_rules_trailer_owner_fkey
carriers --{ deliveries :carrier_id_fkey
carriers --{ carrier_rates :carrier_rates_carrier_id_fkey
carriers --{ carrier_sites :carrier_sites_carrier_id_fkey
carriers --{ customer_carriers :customer_carriers_carrier_id_fkey
carriers --{ deliveries :deliveries_expected_broker_id_fkey
carriers --{ tractors :tractors_carrier_id_fkey
carriers --{ trailer_history :trailer_history_broker_id_fkey
carriers --{ trailer_history_tmp :trailer_history_broker_id_fkey
carriers --{ trailer_history :trailer_history_carrier_id_fkey
carriers --{ trailer_history_tmp :trailer_history_carrier_id_fkey
carriers --{ trailer_pool_settings :trailer_pool_settings_carrier_id_fkey
carriers --{ trailer_status :trailer_status_broker_id_fkey
carriers --{ trailer_status :trailer_status_carrier_id_fkey
carriers --{ trailer_tags :trailer_tags_carrier_id_fkey
carriers --{ trailers :trailers_broker_id_fkey
carriers --{ trailers :trailers_carrier_id_fkey
carriers --{ trailers_v2 :trailers_v2_broker_id_fkey
carriers --{ trailers_v2_tmp :trailers_v2_broker_id_fkey
carriers --{ trailers_v2 :trailers_v2_carrier_id_fkey
carriers --{ trailers_v2_tmp :trailers_v2_carrier_id_fkey
carriers --{ user_carriers :user_carriers_carrier_id_fkey
custom_fields --{ custom_field_options :custom_field_options_custom_field_id_fkey
customers --{ customer_carriers :customer_carriers_customer_id_fkey
customers --{ deliveries :deliveries_customer_id_fkey
deliveries --{ assignment_deliveries :assignment_deliveries_delivery_id_fkey
deliveries --{ delivery_groups :delivery_groups_delivery_id_fkey
deliveries --{ expected_load_history :expected_load_history_delivery_id_fkey
deliveries --{ observed_load_history :observed_load_history_delivery_id_fkey
deliveries --{ trailer_history_tmp :trailer_history_expected_outbound_delivery_fkey
deliveries --{ trailers_v2_tmp :trailers_v2_expected_outbound_delivery_fkey
detention_rates --{ carrier_rates :carrier_rates_detention_rate_id_fkey
docks --{ doors :doors_dock_id_fkey
docks --{ locations :locations_dock_id_fkey
doors --{ locations :locations_door_id_fkey
driving_nodes --{ driving_paths :driving_paths_child_node_id_fkey
driving_nodes --{ driving_paths :driving_paths_parent_node_id_fkey
events --{ notifications :notifications_event_id_fkey
fk_addresses --{ fk_fk_addresses :fk_fk_addresses_address_id_fkey
fk_addresses --{ fk_stops :fk_stops_address_id_fkey
fk_stops --{ fk_appointment_stops :fk_appointment_stops_stop_id_fkey
fk_stops --{ fk_tracking_stops :fk_tracking_stops_stop_id_fkey
fk_tracking_loads --{ fk_tracking_stops :fk_tracking_stops_tracking_id_fkey
freight --{ freight_sites :freight_sites_freight_id_fkey
freight --{ item_bundles :item_bundles_freight_id_fkey
gates --{ trailer_checks :trailer_checks_gate_id_fkey
geofences --{ buildings :buildings_geofence_id_fkey
geofences --{ docks :fk_geofence_id
geofences --{ doors :fk_geofence_id
geofences --{ locations :fk_geofence_id
geofences --{ parking_lots :fk_geofence_id
geofences --{ parking_spots :fk_geofence_id
geofences --{ gates :gates_geofence_id_fkey
geofences --{ geofence_site :geofence_site_geofence_id_fkey
geofences --{ sites :sites_geofence_id_fkey
geofences --{ zones :zones_geofence_id_fkey
load_types --{ trailer_status :trailer_status_load_types_id_fkey
load_types --{ trailers_v2 :trailers_v2_load_types_id_fkey
loads --{ deliveries :deliveries_actual_load_id_fkey
loads --{ deliveries :deliveries_scheduled_load_id_fkey
loads --{ expected_load_history :expected_load_history_load_id_fkey
loads --{ item_bundles :item_bundles_load_id_fkey
loads --{ observed_load_history :observed_load_history_load_id_fkey
location_sets --{ delivery_templates :delivery_templates_location_set_id_fkey
location_sets --{ location_set_association :location_set_association_location_set_id_fkey
locations --{ assigned_rules :assigned_rules_location_id_fkey
locations --{ assignments :assignments_location_id_fkey
locations --{ location_move_times :location_move_times_from_location_id_fkey
locations --{ location_move_times :location_move_times_to_location_id_fkey
locations --{ location_set_association :location_set_association_location_id_fkey
locations --{ move_request_task_status :move_request_status_from_location_id_fkey
locations --{ move_request_task_status :move_request_status_to_location_id_fkey
locations --{ move_request_task_status :move_request_task_status_planned_to_location_id_fkey
locations --{ occupancy_sensors :occupancy_sensors_location_id_fkey
locations --{ precool_task_status :precool_task_status_planned_to_location_id_fkey
locations --{ preferred_trailer_locations :preferred_trailer_locations_location_id_fkey
locations --{ refuel_task_status :refuel_task_status_planned_to_location_id_fkey
locations --{ switcher_team_locations :switcher_team_locations_location_id_fkey
locations --{ tasks_v2 :tasks_v2_from_location_id_fkey
locations --{ tasks_v2 :tasks_v2_planned_to_location_id_fkey
locations --{ tasks_v2 :tasks_v2_to_location_id_fkey
locations --{ trailer_history :trailer_history_location_id_fkey
locations --{ trailer_history_tmp :trailer_history_location_id_fkey
locations --{ trailer_status :trailer_status_location_id_fkey
locations --{ trailer_queues :trailerqueues_location_id_fkey
locations --{ trailers_v2 :trailers_v2_first_assigned_processing_location_id
locations --{ trailers_v2 :trailers_v2_last_known_location_id
locations --{ trailers_v2 :trailers_v2_location_id_fkey
locations --{ trailers_v2_tmp :trailers_v2_location_id_fkey
occupancy_sensors --{ occupancy_sensor_events :occupancy_sensor_events_sensor_id_fkey
parking_lots --{ locations :locations_parking_lot_id_fkey
parking_lots --{ parking_spots :parking_spots_parking_lot_id_fkey
parking_spots --{ locations :locations_parking_spot_id_fkey
parking_spots --{ rfid_tag_reads :rfid_tag_reads_closest_parking_spot_id_fkey
product_protection_checks --{ trailer_status :last_pp_fuel_check_id
product_protection_checks --{ trailer_status :last_pp_temp_check_id
product_protection_checks --{ trailer_status :latest_pp_check_id
product_protection_checks --{ trailer_history :trailer_history_last_pp_fuel_check_id
product_protection_checks --{ trailer_history_tmp :trailer_history_last_pp_fuel_check_id
product_protection_checks --{ trailer_history :trailer_history_last_pp_temp_check_id
product_protection_checks --{ trailer_history_tmp :trailer_history_last_pp_temp_check_id
product_protection_checks --{ trailer_history :trailer_history_latest_pp_check_id
product_protection_checks --{ trailer_history_tmp :trailer_history_latest_pp_check_id
product_protection_checks --{ trailers_v2 :trailers_v2_last_pp_fuel_check_id
product_protection_checks --{ trailers_v2_tmp :trailers_v2_last_pp_fuel_check_id
product_protection_checks --{ trailers_v2 :trailers_v2_last_pp_temp_check_id
product_protection_checks --{ trailers_v2_tmp :trailers_v2_last_pp_temp_check_id
product_protection_checks --{ trailers_v2 :trailers_v2_latest_pp_check_id
product_protection_checks --{ trailers_v2_tmp :trailers_v2_latest_pp_check_id
reports --{ report_sites :report_sites_report_id_fkey
reports --{ scheduled_report_emails :scheduled_report_emails_report_id_fkey
rules --{ events :alerts_rule_id_fkey
rules --{ assigned_rules :assigned_rules_rule_id_fkey
scheduled_report_emails --{ scheduled_report_email_addresses :scheduled_report_email_addresses_scheduled_report_email_id_fkey
scheduled_report_emails --{ scheduled_report_email_send_frequencies :scheduled_report_email_send_freq_scheduled_report_email_id_fkey
site_settings --{ site_settings_log :site_settings_log_site_id_fkey
sites --{ events :alerts_site_id_fkey
sites --{ appointments :appointments_site_id_fkey
sites --{ assignment_deliveries :assignment_deliveries_site_id_fkey
sites --{ assignments :assignments_site_id_fkey
sites --{ buildings :buildings_site_id_fkey
sites --{ carrier_rates :carrier_rates_site_id_fkey
sites --{ carrier_sites :carrier_sites_site_id_fkey
sites --{ deliveries :deliveries_destination_id_fkey
sites --{ deliveries :deliveries_origin_id_fkey
sites --{ deliveries :deliveries_site_id_fkey
sites --{ delivery_groups :delivery_groups_site_id_fkey
sites --{ delivery_templates :delivery_templates_site_id_fkey
sites --{ docks :docks_site_id_fkey
sites --{ driving_nodes :driving_nodes_site_id_fkey
sites --{ driving_paths :driving_paths_site_id_fkey
sites --{ fk_addresses :fk_addresses_site_id_fkey
sites --{ trailers :fk_site_id
sites --{ form_layouts :form_layouts_site_id_fkey
sites --{ freight_sites :freight_sites_site_id_fkey
sites --{ gate_events :gate_events_site_id_fkey
sites --{ gates :gates_site_id_fkey
sites --{ geofence_site :geofence_site_site_id_fkey
sites --{ item_bundles :item_bundles_supplier_site_id_fkey
sites --{ move_request_events :move_request_events_site_id_fkey
sites --{ tasks :move_requests_site_id_fkey
sites --{ occupancy_sensors :occupancy_sensors_site_id_fkey
sites --{ page_events :page_events_site_id_fkey
sites --{ parking_lots :parking_lots_site_id_fkey
sites --{ product_protection_settings :product_protection_settings_site_id_fkey
sites --{ reason_codes :reason_codes_site_id_fkey
sites --{ report_sites :report_sites_site_id_fkey
sites --{ rfid_tag_reads :rfid_tags_reads_site_id_fkey
sites --{ rules :rules_site_id_fkey
sites --{ saved_filters :saved_filters_site_id_fkey
sites --{ site_map_info :site_map_info_site_id_fkey
sites --{ site_settings :site_settings_site_id_fkey
sites --{ switcher_status :switcher_status_site_id_fkey
sites --{ switcher_status_summary :switcher_status_summary_site_id_fkey
sites --{ switcher_teams :switcher_teams_site_id_fkey
sites --{ switcher_vehicles :switcher_vehicles_site_id_fkey
sites --{ tasks_v2 :tasks_v2_site_id_fkey
sites --{ temperature_ranges :temperature_ranges_site_id_fkey
sites --{ trailer_checks :trailer_checks_site_id_fkey
sites --{ trailer_events :trailer_events_site_id_fkey
sites --{ trailer_history :trailer_history_fk_site_id
sites --{ trailer_history_tmp :trailer_history_fk_site_id
sites --{ trailer_history :trailer_history_site_owner_id_fkey
sites --{ trailer_history_tmp :trailer_history_site_owner_id_fkey
sites --{ trailer_pool_settings :trailer_pool_settings_site_id_fkey
sites --{ trailer_status :trailer_status_site_id_fkey
sites --{ trailer_status :trailer_status_site_owner_id_fkey
sites --{ trailer_tag_sites :trailer_tag_sites_eligible_site_id_fkey
sites --{ trailer_type_sites :trailer_typ_sites_eligible_site_id_fkey
sites --{ trailers :trailers_site_owner_id_fkey
sites --{ trailers_v2 :trailers_v2_fk_site_id
sites --{ trailers_v2_tmp :trailers_v2_fk_site_id
sites --{ trailers_v2 :trailers_v2_site_owner_id_fkey
sites --{ trailers_v2_tmp :trailers_v2_site_owner_id_fkey
sites --{ user_site_preferences :user_site_preferences_site_id_fkey
sites --{ user_sites :user_sites_site_id_fkey
sites --{ zones :zones_site_id_fkey
subscribers --{ subscriptions :subscriptions_subscriber_id_fkey
subscriptions --{ notifications :notifications_subscription_id_fkey
switcher_event_log --{ switcher_status :switcher_status_switcher_event_log_id_fkey
switcher_status --{ switcher_status :switcher_status_switcher_status_id_fkey
switcher_teams --{ switcher_team_locations :switcher_team_locations_team_id_fkey
switcher_teams --{ switcher_team_memberships :switcher_team_memberships_team_id_fkey
switcher_teams --{ switcher_team_tasks :switcher_team_tasks_team_id_fkey
switcher_teams --{ switcher_team_unassigned_locations :switcher_team_unassigned_locations_team_id_fkey
switcher_teams --{ switcher_team_vehicles :switcher_team_vehicles_team_id_fkey
switcher_vehicles --{ move_request_task_status :move_request_task_status_switcher_vehicle_id_fkey
switcher_vehicles --{ precool_task_status :precool_task_status_switcher_vehicle_id_fkey
switcher_vehicles --{ refuel_task_status :refuel_task_status_switcher_vehicle_id_fkey
switcher_vehicles --{ rfid_tag_reads :rfid_tags_reads_switcher_vehicle_id_fkey
switcher_vehicles --{ switcher_status_summary :switcher_status_summary_switcher_vehicle_id_fkey
switcher_vehicles --{ switcher_status :switcher_status_switcher_vehicle_id_fkey
switcher_vehicles --{ switcher_team_vehicles :switcher_team_vehicles_switcher_vehicle_id_fkey
switcher_vehicles --{ trailer_status :switcher_vehicle_id_fkey
switcher_vehicles --{ tasks_v2 :tasks_v2_switcher_vehicle_id_fkey
switcher_vehicles --{ trailer_history :trailer_history_switcher_vehicle_id_fkey
switcher_vehicles --{ trailer_history_tmp :trailer_history_switcher_vehicle_id_fkey
switcher_vehicles --{ trailers_v2 :trailers_v2_switcher_vehicle_id_fkey
switcher_vehicles --{ trailers_v2_tmp :trailers_v2_switcher_vehicle_id_fkey
tag_types --{ rfid_tag_reads :rfid_tags_reads_tag_type_id_fkey
tag_types --{ trailer_history :trailer_history_tag_type_id_fkey
tag_types --{ trailer_history_tmp :trailer_history_tag_type_id_fkey
tag_types --{ trailer_status :trailer_status_tag_type_id_fkey
tag_types --{ trailer_tags :trailer_tags_tag_type_id_fkey
tag_types --{ trailers_v2 :trailers_v2_tag_type_id_fkey
tag_types --{ trailers_v2_tmp :trailers_v2_tag_type_id_fkey
tasks_v2 --{ move_request_queues :move_request_queues_move_request_id_fkey
tasks_v2 --{ move_request_task_status :move_request_status_move_request_id_fkey
tasks_v2 --{ precool_task_status :precool_task_status_task_id_fkey
tasks_v2 --{ refuel_task_status :refuel_task_status_task_id_fkey
tasks_v2 --{ switcher_status :switcher_status_task_id_fkey
tractors --{ appointments :appointments_tractor_id_fkey
tractors --{ trailer_checks :trailer_checks_tractor_id_fkey
trailer_conditions --{ trailer_status :trailer_status_trailer_condition_id_fkey
trailer_conditions --{ trailers_v2 :trailers_v2_trailer_condition_id_fkey
trailer_status --{ move_request_task_status :move_request_task_status_trailer_status_id_at_task_creation_fke
trailer_status --{ precool_task_status :precool_task_status_trailer_status_id_at_task_creation_fkey
trailer_status --{ refuel_task_status :refuel_task_status_trailer_status_id_at_task_creation_fkey
trailer_status --{ rfid_tag_reads :rfid_tag_reads_trailer_status_id_fkey
trailer_status --{ tasks_v2 :tasks_v2_trailer_status_id_at_task_creation_fkey
trailer_status --{ trailer_checks :trailer_checks_trailer_status_id_fkey
trailer_tags --{ trailer_tag_sites :trailer_tag_sites_trailer_tag_id_fkey
trailer_types --{ carrier_rates :carrier_rates_trailer_type_id_fkey
trailer_types --{ deliveries :deliveries_trailer_type_id_fkey
trailer_types --{ trailer_tags :fk_trailer_type_id
trailer_types --{ trailers :fk_trailer_type_id
trailer_types --{ trailer_history_tmp :trailer_history_trailer_type_id_fkey
trailer_types --{ trailer_history :trailer_history_type_id_fkey
trailer_types --{ trailer_status :trailer_status_trailer_type_id_fkey
trailer_types --{ trailer_type_sites :trailer_type_sites_trailer_type_id_fkey
trailer_types --{ trailers_v2_tmp :trailers_v2_trailer_type_id_fkey
trailer_types --{ trailers_v2 :trailers_v2_type_id_fkey
trailer_usage --{ trailer_status :trailer_status_trailer_usage_id_fkey
trailer_usage --{ trailer_tags :trailer_tags_trailer_usage_id_fkey
trailer_usage --{ trailers_v2 :trailers_v2_trailer_usage_id_fkey
trailers --{ appointments :appointments_inbound_trailer_id_fkey
trailers --{ appointments :appointments_outbound_trailer_id_fkey
trailers --{ assignments :assignments_trailer_id_fkey
trailers --{ deliveries :deliveries_last_associated_trailer_id_fkey
trailers --{ gate_events :gate_events_trailer_id_fkey
trailers --{ move_request_events :move_request_events_trailer_id_fkey
trailers --{ move_request_task_status :move_request_status_trailer_id_fkey
trailers --{ move_request_task_status :move_request_task_status_planned_trailer_id_fkey
trailers --{ precool_task_status :precool_task_status_planned_trailer_id_fkey
trailers --{ precool_task_status :precool_task_status_trailer_id_fkey
trailers --{ preferred_trailer_locations :preferred_trailer_locations_trailer_id_fkey
trailers --{ product_protection_checks :product_protection_checks_trailer_id_fkey
trailers --{ refuel_task_status :refuel_task_status_planned_trailer_id_fkey
trailers --{ refuel_task_status :refuel_task_status_trailer_id_fkey
trailers --{ rfid_tag_reads :rfid_tags_reads_trailer_associated_with_rfid_fkey
trailers --{ tasks_v2 :tasks_v2_planned_trailer_id_fkey
trailers --{ tasks_v2 :tasks_v2_trailer_id_fkey
trailers --{ trailer_checks :trailer_checks_trailer_id_fkey
trailers --{ trailer_events :trailer_events_trailer_id_fkey
trailers --{ trailer_fees :trailer_fees_trailer_id_fkey
trailers --{ trailer_status :trailer_status_trailer_id_fkey
trailers --{ trailer_queues :trailerqueues_trailer_id_fkey
trailers_v2 --{ trailer_history :trailer_history_trailer_id_fkey
trailers_v2_tmp --{ trailer_history_tmp :trailer_history_trailer_id_fkey
users --{ ctpat_settings :ctpat_settings_created_by_fkey
users --{ ctpat_settings :ctpat_settings_updated_by_fkey
users --{ expected_load_history :expected_load_history_user_id_fkey
users --{ move_request_queues :move_request_queues_user_id_fkey
users --{ move_request_task_status :move_request_status_assignee_id_fkey
users --{ move_request_task_status :move_request_status_user_id_fkey
users --{ tasks :move_requests_requestor_id_fkey
users --{ observed_load_history :observed_load_history_user_id_fkey
users --{ page_events :page_events_user_id_fkey
users --{ precool_task_status :precool_task_status_assignee_id_fkey
users --{ precool_task_status :precool_task_status_user_id_fkey
users --{ product_protection_checks :product_protection_checks_user_id_fkey
users --{ refuel_task_status :refuel_task_status_assignee_id_fkey
users --{ refuel_task_status :refuel_task_status_user_id_fkey
users --{ reports :reports_last_modified_by_fkey
users --{ reports :reports_user_id_fkey
users --{ rfid_tag_reads :rfid_tags_reads_switcher_driver_fkey
users --{ saved_filters :saved_filters_user_id_fkey
users --{ site_map_info :site_map_info_created_by_fkey
users --{ site_map_info :site_map_info_updated_by_fkey
users --{ site_settings_log :site_settings_log_user_id_fkey
users --{ subscribers :subscribers_user_id_fkey
users --{ switcher_status_summary :switcher_status_summary_switcher_id_fkey
users --{ switcher_status :switcher_status_switcher_id_fkey
users --{ switcher_team_memberships :switcher_team_memberships_user_id_fkey
users --{ switcher_vehicles :switcher_vehicles_switcher_id_fkey
users --{ tasks_v2 :tasks_v2_assignee_id_fkey
users --{ tasks_v2 :tasks_v2_requestor_id_fkey
users --{ trailer_checks :trailer_checks_guard_id_fkey
users --{ trailer_history :trailer_history_user_id_fkey
users --{ trailer_history_tmp :trailer_history_user_id_fkey
users --{ trailer_pool_settings :trailer_pool_settings_user_id_fkey
users --{ trailer_queues :trailer_queues_requestor_id_fkey
users --{ trailer_status :trailer_status_user_id_fkey
users --{ trailers_v2 :trailers_v2_user_id_fkey
users --{ trailers_v2_tmp :trailers_v2_user_id_fkey
users --{ user_carriers :user_carriers_user_id_fkey
users --{ user_history :user_history_generated_by_fkey
users --{ user_history :user_history_user_id_fkey
users --{ user_site_preferences :user_site_preferences_user_id_fkey
users --{ user_sites :user_sites_user_id_fkey
zones --{ docks :docks_zone_id_fkey
zones --{ doors :doors_zone_id_fkey
zones --{ parking_spots :parking_spots_zone_id_fkey
zones --{ yard_properties :yard_properties_zone_id_fkey
@enduml
